[package]
name = "maowbot"
version = "0.1.0"
edition = "2021"

[dependencies]
twitch_api = {  version="^0.7.0-rc", features = ["client", "helix"] }
sqlx = { version = "^0.8", features = ["sqlite", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "^1", features = ["full"] }
chrono = { version = "^0.4", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^2.0"
anyhow = "^1.0"
dotenv = "^0.15"
uuid = { version = "1.11.0", features = ["v4"] }
async-trait = "0.1.83"
mockall = "0.13.1"
reqwest = "^0.12"
aes-gcm = "^0.11.0-pre"
base64 = "^0.22"
rand = "^0.9.0-beta"
serenity = "^0.12"
url = "^2.5"
oauth2 = "^4.4"

[dev-dependencies]
tokio-test = "^0.4"