[package]
name = "maowbot"
version = "0.1.0"
edition = "2021"

[profile.test]
# ensures the Rust test harness uses only one thread
test-threads = 1

[dependencies]
twitch_api = {  version="^0.7.0-rc", features = ["client", "helix", "reqwest"] }
sqlx = { version = "^0.8", features = ["sqlite", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "^1", features = ["full"] }
tokio-rustls = "0.23"
rustls = "0.21"
rcgen = "0.9"
chrono = { version = "^0.4", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^2.0"
anyhow = "^1.0"
dotenv = "^0.15"
uuid = { version = "1.11.0", features = ["v4"] }
async-trait = "0.1.83"
mockall = "0.13.1"
reqwest = "^0.12"
aes-gcm = "^0.11.0-pre"
base64 = "^0.22"
rand = "^0.8"
rand_core = "^0.6"
serenity = "^0.12"
url = "^2.5"
oauth2 = "^4.4"
clap = {  version = "4.2", features = ["derive"] }

# --- New or updated below:
tracing = "^0.1"
tracing-subscriber = "^0.3"
rustls-pemfile = "1.0.4"
futures-lite = "2.6.0"
tempfile = "3.15.0"

[dev-dependencies]
tokio-test = "^0.4"
