[package]
name = "maowbot"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.test]
# ensures the Rust test harness uses only one thread
test-threads = 1

[dependencies]
twitch_api = {  version="^0.7.0-rc", features = ["client", "helix", "reqwest"] }

sqlx = { version = "^0.8", features = ["sqlite", "runtime-tokio-native-tls", "chrono"] }

tokio = { version = "^1.43", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
tokio-rustls = "0.26"

rcgen = "^0.13"

chrono = { version = "^0.4", features = ["serde"] }

serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"

thiserror = "^2.0"
anyhow = "^1.0"
dotenv = "^0.15"

uuid = { version = "^1.12", features = ["v4"] }
async-trait = "^0.1"
mockall = "0.13.1"
reqwest = "^0.12"
aes-gcm = "^0.11.0-pre"
base64 = "^0.22"
rand = "^0.8"
rand_core = "^0.6"
serenity = "^0.12"
url = "^2.5"
oauth2 = "^4.4"
clap = {  version = "^4.5", features = ["derive"] }

# gRPC / protobuf:
tonic = { version = "^0.10", features = ["transport", "tls"] }
prost = "^0.12"
prost-types = "^0.12"

# --- New or updated below:
tracing = "^0.1"
tracing-subscriber = "^0.3"
rustls-pemfile = "1.0.4"
futures-lite = "2.6.0"
tempfile = "3.15.0"
futures-util = "0.3.31"
futures-core = "0.3.31"


[dev-dependencies]
tokio-test = "^0.4"

[build-dependencies]
tonic-build = "^0.10"