[package]
name        = "maowbot-overlay"
version     = "0.1.0"
edition     = "2021"
build       = "build.rs"

[dependencies]
# ── core ────────────────────────────────────────────────────────────────
bevy          = { version = "0.16", default-features = false, features=[
    "bevy_winit","bevy_render","bevy_asset","bevy_core_pipeline",
    "bevy_scene","bevy_sprite","bevy_text","bevy_ui","png","x11",
] }

bevy_egui     = "0.34"

tokio         = { workspace = true, features=["rt-multi-thread","macros"] }
tonic         = { workspace = true }
tokio-stream  = { workspace = true }

maowbot-proto = { path = "../maowbot-proto" }

tracing       = { workspace = true }

once_cell     = "1"

windows = { version = "0.58.0", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common"
] }

# ── FFI helpers ─────────────────────────────────────────────────────────
libc          = "0.2"

anyhow = { workspace = true }
tracing-subscriber = "0.3.19"

[build-dependencies]
cc = "1.0"
