[package]
name = "maowbot-tui"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }

open = "5.3"

maowbot-core = { path = "../maowbot-core" }

[lib]
name = "maowbot_tui"
crate-type = ["rlib"]
path = "src/lib.rs"